// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.jianhua.netty.serialize.message;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional int64 phoneno = 3;</code>
     */
    boolean hasPhoneno();
    /**
     * <code>optional int64 phoneno = 3;</code>
     */
    long getPhoneno();

    /**
     * <code>repeated string hobby = 4;</code>
     */
    java.util.List<java.lang.String>
        getHobbyList();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    int getHobbyCount();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    java.lang.String getHobby(int index);
    /**
     * <code>repeated string hobby = 4;</code>
     */
    com.google.protobuf.ByteString
        getHobbyBytes(int index);

    /**
     * <code>optional string sex = 5;</code>
     */
    boolean hasSex();
    /**
     * <code>optional string sex = 5;</code>
     */
    java.lang.String getSex();
    /**
     * <code>optional string sex = 5;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
     */
    com.jianhua.netty.serialize.message.UserInfo.User.UserStatus getStatus();

    /**
     * <code>optional .User.Address address = 7;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    com.jianhua.netty.serialize.message.UserInfo.User.Address getAddress();
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      password_ = "";
      phoneno_ = 0L;
      hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sex_ = "";
      status_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              phoneno_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hobby_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hobby_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sex_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.jianhua.netty.serialize.message.UserInfo.User.UserStatus value = com.jianhua.netty.serialize.message.UserInfo.User.UserStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                status_ = rawValue;
              }
              break;
            }
            case 58: {
              com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.jianhua.netty.serialize.message.UserInfo.User.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jianhua.netty.serialize.message.UserInfo.User.class, com.jianhua.netty.serialize.message.UserInfo.User.Builder.class);
    }

    /**
     * Protobuf enum {@code User.UserStatus}
     */
    public enum UserStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ON_LINE = 0;</code>
       */
      ON_LINE(0),
      /**
       * <code>OFF_LINE = 1;</code>
       */
      OFF_LINE(1),
      ;

      /**
       * <code>ON_LINE = 0;</code>
       */
      public static final int ON_LINE_VALUE = 0;
      /**
       * <code>OFF_LINE = 1;</code>
       */
      public static final int OFF_LINE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserStatus valueOf(int value) {
        return forNumber(value);
      }

      public static UserStatus forNumber(int value) {
        switch (value) {
          case 0: return ON_LINE;
          case 1: return OFF_LINE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserStatus>() {
              public UserStatus findValueByNumber(int number) {
                return UserStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jianhua.netty.serialize.message.UserInfo.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserStatus[] VALUES = values();

      public static UserStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:User.UserStatus)
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:User.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string addr = 1;</code>
       */
      boolean hasAddr();
      /**
       * <code>required string addr = 1;</code>
       */
      java.lang.String getAddr();
      /**
       * <code>required string addr = 1;</code>
       */
      com.google.protobuf.ByteString
          getAddrBytes();

      /**
       * <code>optional string postcode = 2;</code>
       */
      boolean hasPostcode();
      /**
       * <code>optional string postcode = 2;</code>
       */
      java.lang.String getPostcode();
      /**
       * <code>optional string postcode = 2;</code>
       */
      com.google.protobuf.ByteString
          getPostcodeBytes();
    }
    /**
     * Protobuf type {@code User.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:User.Address)
        AddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        addr_ = "";
        postcode_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                addr_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                postcode_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jianhua.netty.serialize.message.UserInfo.User.Address.class, com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder.class);
      }

      private int bitField0_;
      public static final int ADDR_FIELD_NUMBER = 1;
      private volatile java.lang.Object addr_;
      /**
       * <code>required string addr = 1;</code>
       */
      public boolean hasAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string addr = 1;</code>
       */
      public java.lang.String getAddr() {
        java.lang.Object ref = addr_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            addr_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string addr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        java.lang.Object ref = addr_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int POSTCODE_FIELD_NUMBER = 2;
      private volatile java.lang.Object postcode_;
      /**
       * <code>optional string postcode = 2;</code>
       */
      public boolean hasPostcode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string postcode = 2;</code>
       */
      public java.lang.String getPostcode() {
        java.lang.Object ref = postcode_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            postcode_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string postcode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPostcodeBytes() {
        java.lang.Object ref = postcode_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          postcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasAddr()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addr_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, postcode_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addr_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, postcode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.jianhua.netty.serialize.message.UserInfo.User.Address)) {
          return super.equals(obj);
        }
        com.jianhua.netty.serialize.message.UserInfo.User.Address other = (com.jianhua.netty.serialize.message.UserInfo.User.Address) obj;

        boolean result = true;
        result = result && (hasAddr() == other.hasAddr());
        if (hasAddr()) {
          result = result && getAddr()
              .equals(other.getAddr());
        }
        result = result && (hasPostcode() == other.hasPostcode());
        if (hasPostcode()) {
          result = result && getPostcode()
              .equals(other.getPostcode());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasAddr()) {
          hash = (37 * hash) + ADDR_FIELD_NUMBER;
          hash = (53 * hash) + getAddr().hashCode();
        }
        if (hasPostcode()) {
          hash = (37 * hash) + POSTCODE_FIELD_NUMBER;
          hash = (53 * hash) + getPostcode().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.jianhua.netty.serialize.message.UserInfo.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.jianhua.netty.serialize.message.UserInfo.User.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code User.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:User.Address)
          com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.jianhua.netty.serialize.message.UserInfo.User.Address.class, com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder.class);
        }

        // Construct using com.jianhua.netty.serialize.message.UserInfo.User.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          addr_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          postcode_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_Address_descriptor;
        }

        public com.jianhua.netty.serialize.message.UserInfo.User.Address getDefaultInstanceForType() {
          return com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance();
        }

        public com.jianhua.netty.serialize.message.UserInfo.User.Address build() {
          com.jianhua.netty.serialize.message.UserInfo.User.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.jianhua.netty.serialize.message.UserInfo.User.Address buildPartial() {
          com.jianhua.netty.serialize.message.UserInfo.User.Address result = new com.jianhua.netty.serialize.message.UserInfo.User.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.addr_ = addr_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.postcode_ = postcode_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.jianhua.netty.serialize.message.UserInfo.User.Address) {
            return mergeFrom((com.jianhua.netty.serialize.message.UserInfo.User.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.jianhua.netty.serialize.message.UserInfo.User.Address other) {
          if (other == com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance()) return this;
          if (other.hasAddr()) {
            bitField0_ |= 0x00000001;
            addr_ = other.addr_;
            onChanged();
          }
          if (other.hasPostcode()) {
            bitField0_ |= 0x00000002;
            postcode_ = other.postcode_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasAddr()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.jianhua.netty.serialize.message.UserInfo.User.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.jianhua.netty.serialize.message.UserInfo.User.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object addr_ = "";
        /**
         * <code>required string addr = 1;</code>
         */
        public boolean hasAddr() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string addr = 1;</code>
         */
        public java.lang.String getAddr() {
          java.lang.Object ref = addr_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              addr_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string addr = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAddrBytes() {
          java.lang.Object ref = addr_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addr_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string addr = 1;</code>
         */
        public Builder setAddr(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          addr_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string addr = 1;</code>
         */
        public Builder clearAddr() {
          bitField0_ = (bitField0_ & ~0x00000001);
          addr_ = getDefaultInstance().getAddr();
          onChanged();
          return this;
        }
        /**
         * <code>required string addr = 1;</code>
         */
        public Builder setAddrBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          addr_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object postcode_ = "";
        /**
         * <code>optional string postcode = 2;</code>
         */
        public boolean hasPostcode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string postcode = 2;</code>
         */
        public java.lang.String getPostcode() {
          java.lang.Object ref = postcode_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              postcode_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string postcode = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPostcodeBytes() {
          java.lang.Object ref = postcode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            postcode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string postcode = 2;</code>
         */
        public Builder setPostcode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          postcode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string postcode = 2;</code>
         */
        public Builder clearPostcode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          postcode_ = getDefaultInstance().getPostcode();
          onChanged();
          return this;
        }
        /**
         * <code>optional string postcode = 2;</code>
         */
        public Builder setPostcodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          postcode_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:User.Address)
      }

      // @@protoc_insertion_point(class_scope:User.Address)
      private static final com.jianhua.netty.serialize.message.UserInfo.User.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.jianhua.netty.serialize.message.UserInfo.User.Address();
      }

      public static com.jianhua.netty.serialize.message.UserInfo.User.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      public com.jianhua.netty.serialize.message.UserInfo.User.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONENO_FIELD_NUMBER = 3;
    private long phoneno_;
    /**
     * <code>optional int64 phoneno = 3;</code>
     */
    public boolean hasPhoneno() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 phoneno = 3;</code>
     */
    public long getPhoneno() {
      return phoneno_;
    }

    public static final int HOBBY_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hobby_;
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbyList() {
      return hobby_;
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public int getHobbyCount() {
      return hobby_.size();
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public java.lang.String getHobby(int index) {
      return hobby_.get(index);
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHobbyBytes(int index) {
      return hobby_.getByteString(index);
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private volatile java.lang.Object sex_;
    /**
     * <code>optional string sex = 5;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sex = 5;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sex_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sex = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
     */
    public com.jianhua.netty.serialize.message.UserInfo.User.UserStatus getStatus() {
      com.jianhua.netty.serialize.message.UserInfo.User.UserStatus result = com.jianhua.netty.serialize.message.UserInfo.User.UserStatus.valueOf(status_);
      return result == null ? com.jianhua.netty.serialize.message.UserInfo.User.UserStatus.OFF_LINE : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 7;
    private com.jianhua.netty.serialize.message.UserInfo.User.Address address_;
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public com.jianhua.netty.serialize.message.UserInfo.User.Address getAddress() {
      return address_ == null ? com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddress()) {
        if (!getAddress().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, phoneno_);
      }
      for (int i = 0; i < hobby_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hobby_.getRaw(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(6, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, getAddress());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, phoneno_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobby_.size(); i++) {
          dataSize += computeStringSizeNoTag(hobby_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHobbyList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jianhua.netty.serialize.message.UserInfo.User)) {
        return super.equals(obj);
      }
      com.jianhua.netty.serialize.message.UserInfo.User other = (com.jianhua.netty.serialize.message.UserInfo.User) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && (hasPhoneno() == other.hasPhoneno());
      if (hasPhoneno()) {
        result = result && (getPhoneno()
            == other.getPhoneno());
      }
      result = result && getHobbyList()
          .equals(other.getHobbyList());
      result = result && (hasSex() == other.hasSex());
      if (hasSex()) {
        result = result && getSex()
            .equals(other.getSex());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && (hasAddress() == other.hasAddress());
      if (hasAddress()) {
        result = result && getAddress()
            .equals(other.getAddress());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      if (hasPhoneno()) {
        hash = (37 * hash) + PHONENO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPhoneno());
      }
      if (getHobbyCount() > 0) {
        hash = (37 * hash) + HOBBY_FIELD_NUMBER;
        hash = (53 * hash) + getHobbyList().hashCode();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jianhua.netty.serialize.message.UserInfo.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jianhua.netty.serialize.message.UserInfo.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.jianhua.netty.serialize.message.UserInfo.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jianhua.netty.serialize.message.UserInfo.User.class, com.jianhua.netty.serialize.message.UserInfo.User.Builder.class);
      }

      // Construct using com.jianhua.netty.serialize.message.UserInfo.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        phoneno_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jianhua.netty.serialize.message.UserInfo.internal_static_User_descriptor;
      }

      public com.jianhua.netty.serialize.message.UserInfo.User getDefaultInstanceForType() {
        return com.jianhua.netty.serialize.message.UserInfo.User.getDefaultInstance();
      }

      public com.jianhua.netty.serialize.message.UserInfo.User build() {
        com.jianhua.netty.serialize.message.UserInfo.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jianhua.netty.serialize.message.UserInfo.User buildPartial() {
        com.jianhua.netty.serialize.message.UserInfo.User result = new com.jianhua.netty.serialize.message.UserInfo.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phoneno_ = phoneno_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hobby_ = hobby_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jianhua.netty.serialize.message.UserInfo.User) {
          return mergeFrom((com.jianhua.netty.serialize.message.UserInfo.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jianhua.netty.serialize.message.UserInfo.User other) {
        if (other == com.jianhua.netty.serialize.message.UserInfo.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasPhoneno()) {
          setPhoneno(other.getPhoneno());
        }
        if (!other.hobby_.isEmpty()) {
          if (hobby_.isEmpty()) {
            hobby_ = other.hobby_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHobbyIsMutable();
            hobby_.addAll(other.hobby_);
          }
          onChanged();
        }
        if (other.hasSex()) {
          bitField0_ |= 0x00000010;
          sex_ = other.sex_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasPassword()) {
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jianhua.netty.serialize.message.UserInfo.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jianhua.netty.serialize.message.UserInfo.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      private long phoneno_ ;
      /**
       * <code>optional int64 phoneno = 3;</code>
       */
      public boolean hasPhoneno() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 phoneno = 3;</code>
       */
      public long getPhoneno() {
        return phoneno_;
      }
      /**
       * <code>optional int64 phoneno = 3;</code>
       */
      public Builder setPhoneno(long value) {
        bitField0_ |= 0x00000004;
        phoneno_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 phoneno = 3;</code>
       */
      public Builder clearPhoneno() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phoneno_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbyIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = new com.google.protobuf.LazyStringArrayList(hobby_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbyList() {
        return hobby_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public int getHobbyCount() {
        return hobby_.size();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public java.lang.String getHobby(int index) {
        return hobby_.get(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHobbyBytes(int index) {
        return hobby_.getByteString(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder setHobby(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobby(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addAllHobby(
          java.lang.Iterable<java.lang.String> values) {
        ensureHobbyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobby_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder clearHobby() {
        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobbyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>optional string sex = 5;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sex_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }

      private int status_ = 1;
      /**
       * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
       */
      public com.jianhua.netty.serialize.message.UserInfo.User.UserStatus getStatus() {
        com.jianhua.netty.serialize.message.UserInfo.User.UserStatus result = com.jianhua.netty.serialize.message.UserInfo.User.UserStatus.valueOf(status_);
        return result == null ? com.jianhua.netty.serialize.message.UserInfo.User.UserStatus.OFF_LINE : result;
      }
      /**
       * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
       */
      public Builder setStatus(com.jianhua.netty.serialize.message.UserInfo.User.UserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .User.UserStatus status = 6 [default = OFF_LINE];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 1;
        onChanged();
        return this;
      }

      private com.jianhua.netty.serialize.message.UserInfo.User.Address address_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jianhua.netty.serialize.message.UserInfo.User.Address, com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder, com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.jianhua.netty.serialize.message.UserInfo.User.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder setAddress(com.jianhua.netty.serialize.message.UserInfo.User.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder setAddress(
          com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder mergeAddress(com.jianhua.netty.serialize.message.UserInfo.User.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              address_ != null &&
              address_ != com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance()) {
            address_ =
              com.jianhua.netty.serialize.message.UserInfo.User.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.jianhua.netty.serialize.message.UserInfo.User.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jianhua.netty.serialize.message.UserInfo.User.Address, com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder, com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jianhua.netty.serialize.message.UserInfo.User.Address, com.jianhua.netty.serialize.message.UserInfo.User.Address.Builder, com.jianhua.netty.serialize.message.UserInfo.User.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.jianhua.netty.serialize.message.UserInfo.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jianhua.netty.serialize.message.UserInfo.User();
    }

    public static com.jianhua.netty.serialize.message.UserInfo.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.jianhua.netty.serialize.message.UserInfo.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\"\363\001\n\004User\022\014\n\004name\030\001 \002(\t\022\020\n\010p" +
      "assword\030\002 \002(\t\022\017\n\007phoneno\030\003 \001(\003\022\r\n\005hobby\030" +
      "\004 \003(\t\022\013\n\003sex\030\005 \001(\t\022*\n\006status\030\006 \001(\0162\020.Use" +
      "r.UserStatus:\010OFF_LINE\022\036\n\007address\030\007 \001(\0132" +
      "\r.User.Address\032)\n\007Address\022\014\n\004addr\030\001 \002(\t\022" +
      "\020\n\010postcode\030\002 \001(\t\"\'\n\nUserStatus\022\013\n\007ON_LI" +
      "NE\020\000\022\014\n\010OFF_LINE\020\001B/\n#com.jianhua.netty." +
      "serialize.messageB\010UserInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Name", "Password", "Phoneno", "Hobby", "Sex", "Status", "Address", });
    internal_static_User_Address_descriptor =
      internal_static_User_descriptor.getNestedTypes().get(0);
    internal_static_User_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_Address_descriptor,
        new java.lang.String[] { "Addr", "Postcode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
